### ISSUE TITLE
"Add to Backpack" uses incorrect "_ of _" block

### ISSUE THREAD

**Issue by Airhogs777** [tjvr/scratchblocks#189]
reported on https://scratch.mit.edu/discuss/topic/210264/

In the forums:
![screen shot 2016-07-24 at 11 48 53 pm](https://cloud.githubusercontent.com/assets/2879020/17091635/447cc528-51f9-11e6-881c-5ac8e2fbcafe.png)

In my backpack:
![screen shot 2016-07-24 at 11 47 56 pm](https://cloud.githubusercontent.com/assets/2879020/17091634/447c85d6-51f9-11e6-9ad8-5dee7bdf49d5.png)

In the editor:
![screen shot 2016-07-24 at 11 50 06 pm](https://cloud.githubusercontent.com/assets/2879020/17091671/aeabc8d6-51f9-11e6-8e81-ef66809069e8.png)

**Comment by tjvr** [comment]
You can't use `:: operators` hacks with the "Add to backpack" feature.

Possibly we should disable JSON export if you use any of these.

**Comment by liam4** [comment]
> You can't use `:: operators` hacks with the "Add to backpack" feature.

Why not?

These are handy blocks to have. I don't agree with just getting rid of a feature because it's not perfect the way it is.. just make it better?

Though I do agree that `:: operators` is a bit on the yucky side.. but it *does* make sense!

Anyways blame the Scratch Team for having both a math-of block and an attribute-of block, each with the same spec. :)

**Comment by tjvr** [comment]
> Why not?

That is not the intention of the JSON export feature.

Category/shape `::` hacks are designed for customising the _display_ of the output; they don't affect JSON export.

We already have disambiguation of the two "of" blocks in most cases, by matching on the contents of the first input (ie. is it a math function name?). I've never seen a Scratch project that puts a reporter in the function input.
